#!/bin/sh
# vfile - ファイルに関する処理を実行する

# The MIT License (MIT)
#
# Copyright (c) 2015 yhirano-.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

########################################################################

# CRLFをLFに変換する
function rv_unix() {
	rm -f $FILENAME.tmp
	tr -d '\r' < $FILENAME > $FILENAME.tmp
	mv -f $FILENAME.tmp $FILENAME
	rm -f $FILENAME.tmp
}

# Shift-JISをUTF8に変換する
function v_utf8() {
	rm -f $FILENAME.tmp
	iconv -f Shift-JIS -t UTF8 $FILENAME > $FILENAME.tmp
	mv -f $FILENAME.tmp $FILENAME
	rm -f $FILENAME.tmp
}

# UTF8をShift-JISに変換する
function v_sjis() {
	rm -f $FILENAME.tmp
	iconv -f UTF8 -t Shift-JIS $FILENAME > $FILENAME.tmp
	mv -f $FILENAME.tmp $FILENAME
	rm -f $FILENAME.tmp
}

########################################################################

function usage() {
	case `vlang` in
	ja)
		echo "Usage: vfile command"
		echo "	unix file-name - CRLFをLFに変換する"
		echo "	utf8 file-name - Shift-JISをUTF8に変換する"
		echo "	sjis file-name - UTF8をShift-JISに変換する"
		;;
	*)
		echo "Usage: vfile command"
		;;
	esac
	echo ""
	echo "Samples:"
	echo "vfile unix windows.txt"
	echo "vfile utf8 sjis.txt"
	echo "vfile sjis utf8.txt"
	exit 1
}

COMMAND=$1

case $COMMAND in
unix)
	FILENAME=$2
	if [ "$FILENAME" == "" ]; then
		usage
	fi
	;;
utf8)
	FILENAME=$2
	if [ "$FILENAME" == "" ]; then
		usage
	fi
	;;
sjis)
	FILENAME=$2
	if [ "$FILENAME" == "" ]; then
		usage
	fi
	;;
*)
	usage
	;;
esac

v_$COMMAND

