#!/bin/sh
# vgit - gitを使った処理を実行する

# The MIT License (MIT)
#
# Copyright (c) 2015 yhirano-.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

########################################################################

function v_confirm() {
	echo $CMD "? [y/N]"
	read answer
	if [ "$answer" != "y" ]; then
		exit 1
	fi
}

# リポジトリにコミットする改行コードをLFにする
function v_autocrlf() {
	git config --global core.autocrlf true
	git config --global core.safecrlf true
}

# 現在のブランチでoriginにpushする
function v_push() {
	BRANCH=`git status | awk '/On branch/ { print $4 }'`
	CMD="git push origin $BRANCH"
	v_confirm
	$CMD
}

# 修正前の状態に戻す
function v_reset() {
	git reset --hard HEAD
}

# リモートリポジトリをタグを含めて取得する
function v_pull() {
    git fetch --tags
    git merge
}

########################################################################

function usage() {
	case `vlang` in
	ja)
		echo "Usage: vgit command"
		echo "	autocrlf - リポジトリにコミットする改行コードをLFにする"
		echo "	push - 現在のブランチでoriginにpushする"
		;;
	*)
		echo "Usage: vgit command"
		;;
	esac
	echo ""
	echo "Samples:"
	echo "vgit autocrlf"
	echo "vgit push"
	exit 1
}

COMMAND=$1

case $COMMAND in
autocrlf)
	;;
push)
	;;
pull)
	;;
reset)
	;;
*)
	usage
	;;
esac

v_$COMMAND

