#!/bin/sh
# vsetup - vを使うための設定を行う

# The MIT License (MIT)
#
# Copyright (c) 2015 yhirano-.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

########################################################################

# [1回だけ実行すればいい] vディレクトリにパスを通す
function v_install() {
	if [ ! -f vsetup ]; then
		echo "do in v directory."
		exit 1
	fi
	echo '
PATH=$PATH:'`pwd`'
export PATH
' >> ~/.bash_profile
	chmod +x v*
	echo 'do run: source ~/.bash_profile'
	echo "echo en" > vlang
}

function v_ja() {
	if [ ! -f vsetup ]; then
		echo "do in v directory."
		exit 1
	fi
	echo "echo ja" > vlang
}

function v_en() {
	if [ ! -f vsetup ]; then
		echo "do in v directory."
		exit 1
	fi
	echo "echo en" > vlang
}

function v_git() {
	# git completion
	echo '' >> ~/.bashrc
}

########################################################################

function usage() {
	echo "Usage: vsetup install"
	echo "install - initialize v."
	echo "en      - use english messages."
	echo "ja      - use japanese messages."
	echo "proxy   - use proxy."
	echo "noproxy - not use proxy."
	echo ""
	echo "Samples:"
	echo "vsetup install"
	echo "vsetup en"
	echo "vsetup ja"
	echo "vsetup proxy"
	echo "vsetup noproxy"
	exit 1
}

COMMAND=$1

case $COMMAND in
install)
	;;
en)
	;;
ja)
	;;
proxy)
	;;
noproxy)
	;;
git)
	;;
*)
	usage
	;;
esac

v_$COMMAND
